### ISSUE TITLE
Correct .travis.yml

### ISSUE THREAD

**Issue by tomschr** [mschnitzer/dapsenv#6]
Maybe a tiny thing, but I would try to be consistent with other Python projects.  I would suggest two changes:

1. move the install part of dapsenv into the install section.
2. use `py.test` in the script section directly.

```yml
install:
    - pip install -r requirements.txt
    - python3 setup.py install

script:
    - py.test
```

I suspect, the `setup.py test` call is unnecessary or even harmful (don't remember were to read it). Additionally, code coverage could be easily added through options.

Goes with issue #5.
